#name, main, version and api are required
name: ShmozoElo
main: Proxying\ShmozoElo
version: 1.0.0
api: [3.0.0-ALPHA7]

author: Proxying
description: Example plugin showing the new API
website: https://github.com/PocketMine/ExamplePlugin
commands:
 example:
  description: Example command
  usage: "Usage: /example"
  permission: exampleplugin.command.example
permissions:
 exampleplugin.command.example:
  description: "Allows the user to run the example command"
  default: true